// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqz-sb0ldpFdVUaLNnLApPZ1cnL8f-T8',
    appId: '1:308593416369:web:aded44f8958dadb054aa90',
    messagingSenderId: '308593416369',
    projectId: 'insideout-8c405',
    authDomain: 'insideout-8c405.firebaseapp.com',
    storageBucket: 'insideout-8c405.appspot.com',
    measurementId: 'G-XP85YM6R7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQh0Rk4EkktjptrsVVpAnzDhnwNxjGqdw',
    appId: '1:308593416369:android:92354b07880b445054aa90',
    messagingSenderId: '308593416369',
    projectId: 'insideout-8c405',
    storageBucket: 'insideout-8c405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXNJBCdVpL_2qa8JqXQ-cEntuzCxBXev8',
    appId: '1:308593416369:ios:506b91123bdfddd054aa90',
    messagingSenderId: '308593416369',
    projectId: 'insideout-8c405',
    storageBucket: 'insideout-8c405.appspot.com',
    iosBundleId: 'com.lvher.insideout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXNJBCdVpL_2qa8JqXQ-cEntuzCxBXev8',
    appId: '1:308593416369:ios:506b91123bdfddd054aa90',
    messagingSenderId: '308593416369',
    projectId: 'insideout-8c405',
    storageBucket: 'insideout-8c405.appspot.com',
    iosBundleId: 'com.lvher.insideout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJqz-sb0ldpFdVUaLNnLApPZ1cnL8f-T8',
    appId: '1:308593416369:web:0dcf5e656768d8d154aa90',
    messagingSenderId: '308593416369',
    projectId: 'insideout-8c405',
    authDomain: 'insideout-8c405.firebaseapp.com',
    storageBucket: 'insideout-8c405.appspot.com',
    measurementId: 'G-7D7T15Q1ZZ',
  );
}
